"""init

Revision ID: 235d213ace3b
Revises: 
Create Date: 2026-06-24 11:28:15.391873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '235d213ace3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dreams',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('mood', sa.String(length=60), nullable=True),
    sa.Column('style', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'GRAPHING', 'STORYBOARDING', 'RENDERING_IMAGES', 'RENDERING_VIDEO', 'COMPLETED', 'FAILED', name='dream_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dreams_user_id'), 'dreams', ['user_id'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('NLP_PARSER', 'SCENE_GRAPH_BUILDER', 'STORYBOARD_GENERATOR', 'IMAGE_GENERATOR', 'VIDEO_GENERATOR', name='pipeline_stage'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_dream_id'), 'pipeline_jobs', ['dream_id'], unique=False)
    op.create_table('scene_graphs',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_graphs_dream_id'), 'scene_graphs', ['dream_id'], unique=False)
    op.create_table('storyboards',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('scene_graph_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_graph_id'], ['scene_graphs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboards_dream_id'), 'storyboards', ['dream_id'], unique=False)
    op.create_table('storyboard_panels',
    sa.Column('storyboard_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=True),
    sa.Column('camera_notes', sa.String(length=255), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', name='panel_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboard_panels_storyboard_id'), 'storyboard_panels', ['storyboard_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('dream_id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='media_type'), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['storyboard_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_dream_id'), 'media_assets', ['dream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_dream_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_storyboard_panels_storyboard_id'), table_name='storyboard_panels')
    op.drop_table('storyboard_panels')
    op.drop_index(op.f('ix_storyboards_dream_id'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index(op.f('ix_scene_graphs_dream_id'), table_name='scene_graphs')
    op.drop_table('scene_graphs')
    op.drop_index(op.f('ix_pipeline_jobs_dream_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_dreams_user_id'), table_name='dreams')
    op.drop_table('dreams')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
